name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.app

      - name: Install dependencies
        run: |
          brew install cmake
          brew install ninja

      - name: Generate Xcode project
        run: |
          mkdir build
          cd build
          cmake -G "Xcode" ..

      - name: Build the project
        run: |
          cd build
          xcodebuild -project GuiApp.xcodeproj -scheme GuiApp -configuration Debug -sdk iphoneos

      - name: Archive the app
        run: |
          cd build
          xcodebuild -project GuiApp.xcodeproj -scheme GuiApp -configuration Debug -sdk iphoneos -archivePath build/GuiApp.xcarchive archive

      - name: Export the IPA
        run: |
          cd build
          xcodebuild -exportArchive -archivePath build/GuiApp.xcarchive -exportPath build/GuiApp -exportOptionsPlist ../ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: GuiApp.ipa
          path: build/GuiApp/GuiApp.ipa
